const IMGS_DB = [
  {
    id: 'tWqqh4',
    name: 'angry trump',
    url: 'img/memes/1.jpg',
    keywords: ['angry', 'politics'],
  },
  {
    id: 'kue3es',
    name: 'puppies',
    url: 'img/memes/2.jpg',
    keywords: ['cute', 'pets'],
  },
  {
    id: 'VvvNhB',
    name: 'sleeping baby and puppy',
    url: 'img/memes/3.jpg',
    keywords: ['baby', 'cute', 'pets'],
  },
  {
    id: 'iUdi5k',
    name: 'sleeping cat',
    url: 'img/memes/4.jpg',
    keywords: ['cute', 'pets'],
  },
  {
    id: 'yTYK4X',
    name: 'success baby',
    url: 'img/memes/5.jpg',
    keywords: ['baby'],
  },
  {
    id: 'cLP5E4',
    name: 'aliens history channel',
    url: 'img/memes/6.jpg',
    keywords: ['tv'],
  },
  {
    id: '4jQN4V',
    name: 'surprised baby',
    url: 'img/memes/7.jpg',
    keywords: ['cute', 'funny'],
  },
  {
    id: 'I4p9WG',
    name: 'tell me more wonka',
    url: 'img/memes/8.jpg',
    keywords: ['movies', 'sarcastic'],
  },
  {
    id: 'VISPH6',
    name: 'evil baby',
    url: 'img/memes/9.jpg',
    keywords: ['cute', 'funny', 'baby'],
  },
  {
    id: 'u5gsQv',
    name: 'laughing obama',
    url: 'img/memes/10.jpg',
    keywords: ['funny', 'politics'],
  },
  {
    id: 'aKsOkl',
    name: 'kissing guys',
    url: 'img/memes/11.jpg',
    keywords: ['nohomo', 'funny'],
  },
  {
    id: 'MiXKqj',
    name: 'what would you do',
    url: 'img/memes/12.jpg',
    keywords: ['celeb', 'tv'],
  },
  {
    id: 'ZYD96Y',
    name: 'dicaprio cheers',
    url: 'img/memes/13.jpg',
    keywords: ['party', 'movies'],
  },
  {
    id: '6it4RE',
    name: 'what if i told you',
    url: 'img/memes/14.jpg',
    keywords: ['celeb', 'movies'],
  },
  {
    id: 'loqo4n',
    name: 'one does not simply',
    url: 'img/memes/15.jpg',
    keywords: ['movies'],
  },
  {
    id: 'RSgwBO',
    name: 'laughing captain',
    url: 'img/memes/16.jpg',
    keywords: ['movies', 'funny'],
  },
  {
    id: 'n9hhmN',
    name: 'putin peace',
    url: 'img/memes/17.jpg',
    keywords: ['celeb'],
  },
  {
    id: 'v44wPs',
    name: 'look at all',
    url: 'img/memes/18.jpg',
    keywords: ['movies'],
  },
  {
    id: 'KofgnD',
    name: 'sounds of music everywhere',
    url: 'img/memes/19.jpg',
    keywords: ['movies'],
  },
  {
    id: '7cFEvD',
    name: 'oprah everybody',
    url: 'img/memes/20.jpg',
    keywords: ['tv', 'celeb'],
  },
  {
    id: 'GyRJbk',
    name: 'flexing dog',
    url: 'img/memes/21.jpg',
    keywords: ['pets', 'funny'],
  },
  {
    id: 'cJdz9b',
    name: 'dancing children africa',
    url: 'img/memes/22.jpg',
    keywords: ['funny'],
  },
  {
    id: 'NZiMjB',
    name: 'angry guy',
    url: 'img/memes/23.jpg',
    keywords: ['movies', 'angry'],
  },
  {
    id: 'kUnzxh',
    name: 'angy trump 2',
    url: 'img/memes/24.jpg',
    keywords: ['angry', 'funny', 'politics'],
  },
  {
    id: 'FS6DeG',
    name: 'dr evil quote',
    url: 'img/memes/25.jpg',
    keywords: ['movies'],
  },
];

const MEME_INIT = {
  selectedImgId: 1,
  selectedLineIdx: 0,
  lines: [
    {
      txt: 'Top Line',
      size: 30,
      align: 'center',
      strokeColor: '#000000',
      fillColor: '#FFFFFF',
      fontFamily: 'Impact',
      posX: null,
      posY: null,
      isDragging: false,
    },
    {
      txt: 'Bottom Line',
      size: 30,
      align: 'center',
      strokeColor: '#000000',
      fillColor: '#FFFFFF',
      fontFamily: 'Impact',
      posX: null,
      posY: null,
      isDragging: false,
    },
  ],
};

const SEARCH_SCORES_INIT = {
  funny: 5,
  custom: 10,
  pets: 7,
  movies: 4,
  trump: 6,
  politics: 5,
  tv: 4,
  obama: 4,
  kid: 5,
  baby: 3,
};
